trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/bin/Release/netcoreapp2.2'
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)/Roentgenium.Release'

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/Roentgenium.Release'
    azureSubscription: 'Pay-As-You-Go(e382f751-6823-4da1-9064-c6f60e4066d6)'
    Destination: 'AzureBlob'
    storage: 'roentgenium'
    ContainerName: 'rg-build-artifacts'